# Taps
tap "caskroom/cask"
tap "caskroom/eid"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "homebrew/bundle"

# Cask Dependencies
brew "mas"
cask "java"

# Shells
brew "bash"
brew "zsh"
brew "zsh-completions"

# CLI Utilities
brew "coreutils"
brew "git"
brew "grep"
brew "tree"
brew "wget"

# macOS Tools
brew "mackup"
brew "trash"

# Development
brew "go"
brew "node"
brew "php"

# Apps
cask "1password"
cask "adobe-creative-cloud"
cask "alfred"
cask "bear"
cask "caffeine"
cask "clocker"
cask "docker"
cask "droplr"
cask "eid-pt"
cask "google-cloud-sdk"
cask "grammarly"
cask "iterm2"
cask "now"
cask "postbox"
cask "postman"
cask "sequel-pro"
cask "slack"
cask "tableplus"
cask "tower"
cask "vlc"
cask "visual-studio-code"

# Screensavers
cask "aerial"

# Browsers
cask "firefox"
cask "google-chrome"

# Quicklook
cask "qlcolorcode"
cask "qlmarkdown"
cask "quicklook-json"
cask "quicklook-csv"
cask "qlstephen"

# Fonts
cask "font-source-code-pro-for-powerline"
cask "font-source-code-pro"
cask "font-source-sans-pro"
cask "font-source-serif-pro"
